### PR TITLE
Updated a whole bunch of modules

### PR DESCRIPTION
**Pull request by damienmckenna**

### CODE REVIEW

**Comment by nicxvan** [comment]
This looks pretty good, typically I try to update these with the COD distribution so I'm in sync with them.

I'm a bit behind though so this shouldn't be a problem.

**Comment by damienmckenna** [comment]
Updating COD would require some regression testing, and I didn't know how much customizations you'd made.

**Comment by nicxvan** [comment]
Actually, did you happen to review the patches COD applies? There are some in Views, Commerce, and OG If not I can apply them

**Comment by damienmckenna** [comment]
I did not.

**Pull request merged**
